name: Upload dotnet package

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: dotnet build --configuration Release . 
      - name: Create the package
        run: dotnet pack --configuration Release /p:Version=${{github.event.release.tag_name}} . 
      - name: Publish the package to GPR
        run: dotnet nuget push ./bin/Release/*.nupkg --api-key ${{secrets.NUGET_AUTH_TOKEN}} --source https://api.nuget.org/v3/index.json
